### ISSUE TITLE
dom with async behavior loading

### ISSUE THREAD

**Issue by dtnorris** [elementaljs/elementaljs#14]
Maybe I just don't know how to do this properly but when we have sections of our page that load via an ajax request that have data-behavior elemental functions on them they don't seem loaded by the Elemental.load() call in document ready. I believe this is because document ready is not called again on that subsection of the page. In those cases we have to do another Elemental.load() in that view which seems to defeat the point of Elemental for us.

Is there a right way to do this or is this something that is missing from Elemental?

**Comment by alse** [comment]
Hey @robb1e, I was experimenting with adding a DOM observer and just saw this thread.

A DOM replacement addon would be better for browser compatibility, but I used the MutationObserver api to observe DOM changes. http://caniuse.com/#feat=mutationobserver

Here's my code - I didn't use a separate observer https://github.com/elementaljs/elementaljs/compare/master...alse:observe

**Comment by robb1e** [comment]
Very interesting. Should this be configurable given it could be a change of behaviour? Also, how well is MutationObserver supported by various browsers and versions?

**Comment by alse** [comment]
@robb1e it's currently configurable by adding an observe=true data attribute.

```js
if (($element).data('observe')) {
  observer.observe($element[0], { childList: true });
}
```

I could also add a global option so that all behavior containers can be observed for changes.

Here is the the current browser support for MutationObserver: http://caniuse.com/#feat=mutationobserver
