### ISSUE TITLE
WebJar Version

### ISSUE THREAD

**Issue by spilth** [elementaljs/elementaljs#31]
I'd love to see a [WebJar](http://www.webjars.org/) release of ElementJS

**Comment by robb1e** [comment]
@spilth in a new repo? In this one? How would be best manifest?

**Comment by spilth** [comment]
I think we make a new repo that does the work of generating the WebJar. I'm happy to look into this. I just like making issues to help start the conversation of wether it's even desired.

**Comment by spilth** [comment]
For reference: http://www.webjars.org/contributing

**Comment by geoffwa** [comment]
Isn't https://bintray.com/webjars/maven/org.webjars.bower%3Aelementaljs/view good enough? ;)

**Comment by spilth** [comment]
This didn't come up when I searched for `elementaljs` on the WebJars site.

**Comment by geoffwa** [comment]
@spilth if you go to the bower section of the webjars site (http://www.webjars.org/bower) and click 'Add a New Bower WebJar' you can create webjars from bower packages - I triggered this for elementaljs at around 6PM today, but I guess it rebuilds its index infrequently at best.

**Comment by spilth** [comment]
Ah, I guess I just assumed if it wasn't already listed then it wasn't available via bower.

**Comment by robb1e** [comment]
So covered?

**Comment by spilth** [comment]
Thanks to @geoffwa this is now a thing:

```xml
<dependency>
    <groupId>org.webjars.bower</groupId>
    <artifactId>elementaljs</artifactId>
    <version>1.0.2</version>
</dependency>
```
